version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-west-2:111810594106:task-definition/umami-service:47"
        LoadBalancerInfo:
          ContainerName: "umami"
          ContainerPort: 3000
