name: Deploy via CodeDeploy

on:
  workflow_run:
    workflows: ["CODE TRIGGER with OIDC"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    permissions:
      id-token: write
      contents: read

    env:
      AWS_REGION: eu-west-2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::111810594106:role/ecs-push
          aws-region: ${{ env.AWS_REGION }}

      - name: Trigger CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ecs_code_deployment \
            --deployment-group-name ecs-blue-green \
            --region eu-west-2 \
            --revision revisionType=AppSpecContent,appSpecContent="{\"content\": $(jq -Rs . < appspec.yml)}"
