name: Automating image push to AWS ECR with OIDC

on: [push]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_ID: 175680165464

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:  
          role-to-assume: arn:aws:iam::175680165464:role/github-actions-ecer
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region eu-west-2 \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.eu-west-2.amazonaws.com

      - name: Build and Publish
        run: |
          registry="$AWS_ACCOUNT_ID.175680165464.dkr.ecr.eu-west-2.amazonaws.com/web-plane"
          sha=$(git rev-parse --short HEAD)
          primary_tag="${registry}:${sha}"

          docker build -t $primary_tag -f apps/web/Dockerfile.web ./apps/web.
          docker push $primary_tag

          current_branch=$(git rev-parse --abbrev-ref HEAD)
          if [ "$current_branch" = "main" ]; then
            retention_tag="${registry}:latest"
            docker tag $primary_tag $retention_tag
            docker push $retention_tag
          fi
